import { ReactNode } from 'react'
import { Header } from '@/components/header'
import './globals.css'
import { Saira } from 'next/font/google'
import { DefaultProviders } from '@/components/default-providers'
import ToasterProvider from '@/providers/ToasterProvider'

const saira = Saira({
  weight: ['300', '400', '500', '600'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <DefaultProviders>
          <ToasterProvider />
          <Header />
          {children}
        </DefaultProviders>
      </body>
    </html>
  )
}
